### ISSUE TITLE
Add support for `examples` in request and response bodies properties

### ISSUE THREAD

**Issue by silverbullettruck2001** [Rhosys/openapi-explorer#72] opened 2022-07-27 16:45 UTC
When providing `examples` arrays within the request and response bodies, please include the examples in the displayed models so that the examples show as additional attributes like `Default`, `Allowed` and `Constraints` at a property level.

**Comment by wparad** [comment] 2022-07-28 09:49
I took a look at some functionality we already have, and for example we have the `example` tab for the response body. So what's missing there? For the request body I think we can decide what's the best way to expose this information after we get an example spec.

![image](https://user-images.githubusercontent.com/5056218/181476538-1a35f93a-0316-46df-8a01-34fc5ba8ff83.png)


Does that make sense?

**Comment by wparad** [comment] 2022-07-28 13:45
I've added the `Example` to be shown inline with the description if it exists. If this doesn't work for you or needs an extension, feel free to comment here or open another issue.

**Comment by silverbullettruck2001** [comment] 2022-08-12 10:44
@wparad I have been trying this out, but I am not sure if I am doing it correctly.  When I add an example to a response body I am not seeing anything different in the UI.  Here's an example of what I am using:

```
{
   "openapi": "3.1.0",
   "info": {
      "description": "This is the API Documentation",
      "version": "1.0.0",
      "title": "Test API",
      "termsOfService": "none",
      "contact": {
         "email": "support@test.com"
      }
   },
   "servers": [
      {
         "url": "https://testserver:{port}/",
         "description": "API server",
         "variables": {
            "port": {
               "enum": [
                  "443"
               ],
               "default": "443"
            }
         }
      }
   ],
   "security": [
      {
         "basicAuth": []
      }
   ],
   "paths": {
      "/fsps/{uri_test}/testendpoint": {
         "get": {
            "tags": [
               "test endpoint"
            ],
            "summary": "get testendpoint",
            "responses": {
               "200": {
                  "description": "OK",
                  "content": {
                     "application/vnd.test.api+json; version=v1": {
                        "schema": {
                           "$ref": "#/components/schemas/getTestendpointArrayResponse"
                        }
                     }
                  }
               },
               "default": {
                  "description": "error",
                  "content": {
                     "application/vnd.test.api+json; version=v1": {
                        "schema": {
                           "$ref": "#/components/schemas/errors"
                        }
                     }
                  }
               }
            },
            "parameters": [
               {
                  "name": "uri_test",
                  "in": "path",
                  "required": true,
                  "schema": {
                     "type": "string"
                  }
               }
            ]
         }
      }
   },
   "components": {
      "schemas": {
         "errors": {
            "type": "object",
            "required": [
               "httpId",
               "httpStatus",
               "status",
               "request",
               "at",
               "error"
            ],
            "properties": {
               "httpId": {
                  "type": "integer",
                  "examples": {
                     "randomInteger": {
                        "value": 503549,
                        "summary": "httpId value"
                     }
                  }
               },
               "httpStatus": {
                  "type": "string"
               },
               "status": {
                  "type": "string"
               },
               "request": {
                  "type": "string"
               },
               "at": {
                  "type": "string",
                  "format": "date-time"
               },
               "error": {
                  "type": "object",
                  "required": [
                     "number",
                     "message"
                  ],
                  "properties": {
                     "number": {
                        "type": "integer"
                     },
                     "message": {
                        "type": "string"
                     }
                  },
                  "additionalProperties": false
               }
            },
            "additionalProperties": false
         },
         "getTestendpointArrayResponse": {
            "type": "object",
            "required": [
               "httpId",
               "httpStatus",
               "status",
               "request",
               "at",
               "bizdates"
            ],
            "properties": {
               "httpId": {
                  "type": "integer",
                  "examples": {
                     "randomInteger": {
                        "value": 503548,
                        "summary": "httpId value"
                     }
                  }
               },
               "httpStatus": {
                  "type": "string"
               },
               "status": {
                  "type": "string"
               },
               "request": {
                  "type": "string"
               },
               "at": {
                  "type": "string",
                  "format": "date-time"
               },
               "test": {
                  "type": "object",
                  "required": [
                     "testdate",
                     "testInt",
                     "testdate2"
                  ],
                  "properties": {
                     "testdate": {
                        "type": "string",
                        "format": "date",
                        "nullable": true
                     },
                     "testInt": {
                        "type": [
                           "integer",
                           "null"
                        ]
                     },
                     "testdate2": {
                        "type": "string",
                        "format": "date"
                     }
                  }
               }
            },
            "additionalProperties": false
         }
      },
      "securitySchemes": {
         "basicAuth": {
            "type": "http",
            "scheme": "basic"
         }
      }
   }
}
```

**Comment by wparad** [comment] 2022-08-18 06:44
@silverbullettruck2001 are you talking about the httpId property?

**Comment by silverbullettruck2001** [comment] 2022-08-20 11:28
@wparad yes, I just tried testing with that one.

**Comment by wparad** [comment] 2022-08-22 20:06
@silverbullettruck2001 any luck uncovering what the root cause of this problem is? Otherwise we can investigate further

**Comment by silverbullettruck2001** [comment] 2022-08-22 20:34
From all my testing, I could not make this work.  I tried a couple different ways to specify the example to elements in the `properties` object in a `component`.  I did validate that this is correctly setup in the OpenAPI spec file.  If you could investigate from your end, I would appreciate it.  Thanks!

**Comment by wparad** [comment] 2022-08-22 20:57
sure, but I was asking when you looked at this library, if you found anything that would make you think that there was a bug lurking somewhere. If you didn't spend anytime investigating the library, that's fine, it just means I'll need to start at the beginning to do the debugging, was just hoping there was some additional insight.

Thanks for what you provided so far.

**Comment by wparad** [comment] 2022-08-22 21:28
This is fixed in the latest version based on the spec provided and the current documented `examples` from the specification. Hope this works for you.

**Closed** 2022-08-22 21:27 UTC

**Comment by silverbullettruck2001** [comment] 2022-08-23 14:17
@wparad this worked, thanks again!

**Comment by wparad** [comment] 2022-08-23 15:33
Glad to hear it.
