### ISSUE TITLE
Read only arrays/objects are not showing as read only

### ISSUE THREAD

**Issue by max-mathieu** [Rhosys/openapi-explorer#48] opened 2022-03-29 01:05 UTC
Hi there!

I tried hard to find a solution for this, but the code generating the trees and hiding read-only fields is more than I could chew on after a long day at work...

We have some server-side generated fields that are read-only, something like this:
```
        uploadDate:
          type: string
          readOnly: true
          format: timestamp
          example: "2021-07-01T00:00:00.000Z"
        latestFile:
          readOnly: true
          type: object
          properties:
            type:
              type: string
              example: thumbnail_large
            url:
              type: string
              format: url
              example: https://placekitten.com/g/400/400
        formats:
          readOnly: true
          type: array
          items:
            type: string
            example: thumbnail_large
```

Our goal is to, whenever possible, use the same object for POST/PUT as we use for GET, and leverage the fact that the explorer is hiding the read-only fields -- but that's not working for objects and arrays

With the example above, in `GET`, only `uploadDate` shows with the `[R]`:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/2975941/160511780-dcce20cf-9359-41fd-9155-49fabaf59b82.png">

In `POST`/`PUT`, `uploadDate` is hidden correctly, but the other ones show:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/2975941/160511842-6ef1a2b1-f9f3-4cb4-883f-3a698730b4c6.png">

Seems like while `readOnly` primitives are properly displayed in GET, and hidden in POST/PUT, it seems like it's not supported to have `readOnly` for objects and arrays, though there's nothing in the OpenAPI spec that prevents it

Do you think that would be possible to fix this? I tried looking at schema-tree file but seems like objects and arrays are treated very differently than primitives (including in schema-utils), with fields like `::description`, and had no idea where to go from there...

**Comment by baboonmaj** [comment] 2022-03-29 04:33
That seems to be working fine for our Spec, irrespective of it being primitive, object or array

there is a test case too for that https://mrin9.github.io/RapiDoc/examples/readwrite.html#servers

**Comment by baboonmaj** [comment] 2022-03-29 04:35
never mind I commented in a wrong repo

**Comment by wparad** [comment] 2022-03-29 09:21
@baboonmaj it should also work here, however there have been a lot of changes to improve UX that there might have been something over looked.

@max-mathieu I'll take a look and see if there is something out of place. To make sure that we fix any issue with your spec not displaying as expected, it would help to have a minimal reproduction. Can you attach one, that would definitely speed up the fix.

**Comment by wparad** [comment] 2022-03-29 10:59
This has been fixed in the latest version, thanks for the report. If you find anything not working, please let us know..

**Closed** 2022-03-29 10:59 UTC
