### ISSUE TITLE
Include file with relative path

### ISSUE THREAD

**Issue by cnoelle** [Rhosys/openapi-explorer#23] opened 2021-08-19 10:11 UTC
Testing with a json spec, the following leads to the schema not being loaded:

```json
"components": {
    "schemas": {
        "MySchema": {
            "$ref": "./MySchema.json"
        }
    }
}
```
Instead of the model from the json-file, *{recursive: MySchema.json}* will be displayed (no attempt is made to load the file). When I replace the reference with `"$ref": "http://localhost:8080/MySchema.json"`, it works as expected.

**Comment by wparad** [comment] 2021-08-25 12:38
I'm surprised that doesn't work if the full url does work. For the most part we are using https://github.com/swagger-api/swagger-js/issues for schema resolution, so it's possible that there is a bug there, or missing configuration.

But further information would help, could you add a minimally reproducible example with screen shot differences of the two resolutions, and we can try to figure out what is going on.

**Comment by wparad** [comment] 2021-09-03 18:41
Closing due to lack of reproduction.

**Closed by wparad** 2021-09-03 18:41 UTC
